# Generated by Django 4.2.27 on 2026-01-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
